### ISSUE TITLE
Receiving pastry from shop

### ISSUE THREAD

**Issue by pampersrocker** [lab132/PyBake#14]
With a http response you can pass a single file to the client.

To get a fast response from the server I do not want to create the zip on the fly per request.

Due to our tag system we cannot create one single archive which will be returned by to fulfill the request.
The best way I can think if is to pre-pack archives for each tag:
* myPastry-headers.zip`
* myPastry-platformWin32DebugVs2012.zip
* ....

and to send one request for every wanted tag to the shop.

But what about files that have multiple tags?

Or does anyone have a better idea? 
@Manuzor @juliusf ?

**Comment by Manuzor** [comment]
We could store a `tags.json` within the zip file and always deliver the whole package. The client can then only extract those files that pass the tag-filtering. For large pastries, this would mean that a lot of unecessary files will be transmitted, but I don't see a better way if we want to keep tags. Arguably, such large pastries where only a fraction is frequently used are quite silly to begin with. I would rather split out this frequently used part and add it as a dependency to the not-so-frequently used parts.

**Comment by pampersrocker** [comment]
I think the biggest benefit of tags is that it allows you to omit files from other platforms which are most of the time the biggest overhead in a pastry.
But maybe we can add a platform dependency, telling the server I only want to download stuff that belongs to e.g. Win64. The `server` or the `depot` command would then need to split out the platform dependencies.

**Comment by pampersrocker** [comment]
the oven command is now going to create a zip per tag which will be uploaded for the pastry.

**Comment by pampersrocker** [comment]
The shop now needs to retrieve a list of tags we want to have for each pastry.

**Comment by pampersrocker** [comment]
Packages can be retrieved by the server, there are no tags any longer. A single package now represents the idea of tags.
