### ISSUE TITLE
Create shoppingList which describes the needed dependencies.

### ISSUE THREAD

**Issue by pampersrocker** [lab132/PyBake#15]
A "project" file which will be stored per project which uses `PyBake` as dependency manager needs to be defined, named and parsed by the `customer` command to retrieve given `pastries` from the `shop` which address is stored as well in this file.

**Comment by Manuzor** [comment]
But of course, we need a fitting name for that! :smile: Maube `breakfast.json`? :laughing:

**Comment by pampersrocker** [comment]
I would suggest `shoppingList.json`

**Comment by Manuzor** [comment]
This is basically done already. We have a `shoppingList.py` which provides configuration on a per-project basis. It says which pastries are required and what server to use for downloads.

This can be extended later on with callbacks for events during the whole download and install process, for maximum flexibility with PyBake.
