### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by pampersrocker** [lab132/PyBake#17]
We need to choose a license for PyBake, currently this is left out in the `setup.py`

**Comment by Manuzor** [comment]
I don't care what people do with the code :smile: But I guess creative commons with simple attrbution would suffice. I don't know the exact differences between all the licenses, but I think MIT and the Apache 2 license are similar, i.e. "Do what you want, but give credit to the authors" or so.

**Comment by juliusf** [comment]
http://choosealicense.com/licenses/

**Comment by Manuzor** [comment]
MIT sounds great.

**Comment by pampersrocker** [comment]
MIT it is.
