### ISSUE TITLE
Create zips per Pastry

### ISSUE THREAD

**Issue by pampersrocker** [lab132/PyBake#18]
In order to be able to download just the parts you need from a pastry we need to zip all tags separately and upload them individually

**Comment by Manuzor** [comment]
Recipes will create each smaller package and some higher-level packages, which use the smaller package as dependencies, such as a `ezEngineWindows` package, which includes all headers, binaries, and libs for Windows.

**Comment by Manuzor** [comment]
Can create multiple pastries from a recipe now. Also, `depot` accepts more than 1 pastry and also directories now, so you can upload everything in one go.
