### ISSUE TITLE
Use Semantic Versioning for Pastries

### ISSUE THREAD

**Issue by Manuzor** [lab132/PyBake#21]

**Comment by Manuzor** [comment]
First, I wanted to implement a class in PyBake that handles [semantic versioning](https://semver.org), but since there are already a bunch of packages for that, and it's quite tedious to implement something that is 100% compliant with the full 2.0.0 spec, I have decided to wrap some package instead. I will probably be using `semantic_version`.

**Comment by Manuzor** [comment]
OK, it seems the [semantic_version](https://pypi.python.org/pypi/semantic_version/) package is quite awesome and provides many useful features. I'll definitely be using that :smiley:

**Comment by pampersrocker** [comment]
Python - Its not about writing code - its about finding packages.

**Comment by Manuzor** [comment]
Done.
