### ISSUE TITLE
More sophisticated command-line argument parsing

### ISSUE THREAD

**Issue by Manuzor** [lab132/PyBake#4]
I think we agreed on using `argparse`, right?

I have restructured PyBake into a python package on the `oven` branch. I suggest whoever wants to implement usage of `argparse` merges the `oven` branch to their own branch.

Using `argparse` only makes sense in `code/PyBake/__main__.py`, which is the file that is actually being executed when the `PyBake` package is supposed to be executed.

I thought we would create a python module within the PyBake package for each of the commands (such as oven.py), so they could be individually imported and be used from any script, i.e. `import PyBake.oven`. Each of those modules should have a "run" function, that gets a couple of arguments (if any) that are already extracted from the commandline arguments. These run-functions are called from `__main__.py` with the proper arguments extracted from the commandline argument.

Example with oven.py:
~~~{.py}
def run(recipeScript):
  # Do stuff with `recipeScript`, which should be a simple string.
~~~

and within `__main__.py`:
~~~{.py}
@command("oven")
def execute_oven():
  # parse commandline arguments
  from PyBake import oven
  oven.run(argsParser.recipe) # Pass the parsed script name
~~~

**Comment by pampersrocker** [comment]
Started working on this in the argparse ( 830cc4f ) branch
- [x] Commands are now subparsers from argparse
- [x] usage is displayed when missing a command
- [x] help and version flags (-h and -V)
- [x] Commands are called directly from argparse without further parsing (see set_defaults of the individual supparser)

**Comment by pampersrocker** [comment]
I think this is completed as the basic structure is now set up and the individual arguments can be added while implementing the features they belong to.
