### ISSUE TITLE
Put `client` command in its own module

### ISSUE THREAD

**Issue by Manuzor** [lab132/PyBake#5]
Just like with `oven`, the `client` command should be in its own module (`client.py`? :smile:). We also might need a better name for it, if anyone can think of anything. :grinning:

**Comment by pampersrocker** [comment]
customer?

**Comment by pampersrocker** [comment]
This is somewhat blocked by the other missing features. Implementing the client which syncs the stuff with the server makes only sense once the server is up and running.

**Comment by Manuzor** [comment]
The "client" will be split to several commands. One of them is [depot](https://github.com/lab132/PyBake/pull/12).

**Comment by Manuzor** [comment]
The other command will be called `stock` and will take care of downloading and caching packages, as well as filtering for requested tags and deploying the packages, all on the client side.

Once this is up and running, PyBake might already be ready to be used! Milestone 1 is looking good. :smile:

By the way, `stock` was the best I could come up with and I think it fits quite OK-ish. If you can think of a better name, tell me. Keep in mind that we used names of objects so far, such as `oven` and `shop`, so something like `client` won't fit very well.

**Comment by pampersrocker** [comment]
Maybe `basket`? Like shopping basket.

**Comment by Manuzor** [comment]
Good idea! I was not satisfied with having `depot` _and_ `stock`, because they can kind of refer to the same thing, in some sense. `basket` is definitely better. What do you think about `nanny`? :smile: As in, the [maid-of-all-work](http://www.dict.cc/englisch-deutsch/maid+of+all+work.html) for the client? :smile: 

`PyBake stock --location user C:/path/to/shoppingList.json`
`PyBake basket --location user C:/path/to/shoppingList.json`
`PyBake nanny --location user C:/path/to/shoppingList.json`

**Comment by pampersrocker** [comment]
Nanny kind of violates your own naming rule with objects. I would stick to basket.

**Comment by pampersrocker** [comment]
The "client" command are now at least 3 different commands, so this is completed
